name: devbuild

on:
  push:
    branches: [ "dev" ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install Dependecies
       run: brew install ldid
     - name: Compile
       run: make
     
     - name: Upload ipa
       uses: actions/upload-artifact@v3
       with:
        name: weedra1n
        path: packages/weedra1n.ipa

      - name: Upload bootstrap
        uses: actions/upload-artifact@v3
        with:
         name: bootstrap
         path: weedra1n/Required/bootstrap.tar
        
